FROM label-studio-mmdetection AS label-studio-yolov3
RUN cd /label-studio
RUN mkdir checkpoints
# Add more models here when needed
ADD http://download.openmmlab.com/mmdetection/v2.0/yolo/yolov3_d53_mstrain-608_273e_coco/yolov3_d53_mstrain-608_273e_coco-139f5633.pth checkpoints

RUN label-studio-ml init coco-detector --from label_studio/ml/examples/mmdetection/mmdetection.py --force

EXPOSE 8080
EXPOSE 9090